# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import pose_pb2 as proto_dot_pose__pb2


class ActionServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ActionStream = channel.unary_stream(
                '/pose.ActionServer/ActionStream',
                request_serializer=proto_dot_pose__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_pose__pb2.Action.FromString,
                )
        self.SendAction = channel.unary_unary(
                '/pose.ActionServer/SendAction',
                request_serializer=proto_dot_pose__pb2.Action.SerializeToString,
                response_deserializer=proto_dot_pose__pb2.Empty.FromString,
                )


class ActionServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ActionStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ActionServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ActionStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ActionStream,
                    request_deserializer=proto_dot_pose__pb2.Empty.FromString,
                    response_serializer=proto_dot_pose__pb2.Action.SerializeToString,
            ),
            'SendAction': grpc.unary_unary_rpc_method_handler(
                    servicer.SendAction,
                    request_deserializer=proto_dot_pose__pb2.Action.FromString,
                    response_serializer=proto_dot_pose__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pose.ActionServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ActionServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ActionStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/pose.ActionServer/ActionStream',
            proto_dot_pose__pb2.Empty.SerializeToString,
            proto_dot_pose__pb2.Action.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pose.ActionServer/SendAction',
            proto_dot_pose__pb2.Action.SerializeToString,
            proto_dot_pose__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
